{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "981a7e7c-ad68-48c1-b3b7-f0e5dd9ff998",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "import pyodbc\n",
    "\n",
    "# === 1. Caminho para as imagens ===\n",
    "IMG_DIR = 'img/bandeiras'\n",
    "CSV_PATH = 'data/raw/bandeiras.csv'\n",
    "\n",
    "# === 2. Criar DataFrame com id, imagem, url ===\n",
    "arquivos = sorted(os.listdir(IMG_DIR))\n",
    "df = pd.DataFrame({\n",
    "    'id': range(1, len(arquivos) + 1),\n",
    "    'imagem': arquivos,\n",
    "    'url': [f'{IMG_DIR}/{arquivo}' for arquivo in arquivos]\n",
    "})\n",
    "\n",
    "# === 3. Salvar CSV em ./data/raw ===\n",
    "os.makedirs(os.path.dirname(CSV_PATH), exist_ok=True)\n",
    "df.to_csv(CSV_PATH, index=False, encoding='utf-8')\n",
    "print(f'CSV salvo em {CSV_PATH}')\n",
    "\n",
    "# === 4. Conectar ao SQL Server e importar CSV ===\n",
    "try:\n",
    "    conn = pyodbc.connect(\n",
    "        'DRIVER={SQL Server};'\n",
    "        'SERVER=DESKTOP330S;'\n",
    "        'DATABASE=Futel_Mundo;'\n",
    "        'Trusted_Connection=yes;'\n",
    "    )\n",
    "    cursor = conn.cursor()\n",
    "\n",
    "    # Criar tabela se não existir\n",
    "    cursor.execute(\"\"\"\n",
    "    IF OBJECT_ID('dbo.bandeiras', 'U') IS NULL\n",
    "    BEGIN\n",
    "        CREATE TABLE dbo.bandeiras (\n",
    "            id INT PRIMARY KEY,\n",
    "            imagem VARCHAR(255),\n",
    "            url VARCHAR(255)\n",
    "        )\n",
    "    END\n",
    "    \"\"\")\n",
    "    conn.commit()\n",
    "\n",
    "    # Inserir dados no banco\n",
    "    for _, row in df.iterrows():\n",
    "        cursor.execute(\"\"\"\n",
    "            INSERT INTO dbo.bandeiras (id, imagem, url)\n",
    "            VALUES (?, ?, ?)\"\"\",\n",
    "            row['id'], row['imagem'], row['url']\n",
    "        )\n",
    "    conn.commit()\n",
    "    print('Dados inseridos com sucesso no banco Futel_Mundo, tabela bandeiras.')\n",
    "\n",
    "except Exception as e:\n",
    "    print('Erro ao importar para o banco:', e)\n",
    "\n",
    "finally:\n",
    "    if 'cursor' in locals():\n",
    "        cursor.close()\n",
    "    if 'conn' in locals():\n",
    "        conn.close()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
